default_agent: agentcore_memory
agents:
  agentcore_lang_runtime:
    name: agentcore_lang_runtime
    entrypoint: /Users/sanjaydevarajan/Desktop/ML Projects/AgentCore/agentcore_runtime.py
    deployment_type: container
    runtime_type: null
    platform: linux/arm64
    container_runtime: docker
    source_path: /Users/sanjaydevarajan/Desktop/ML Projects/AgentCore
    aws:
      execution_role: arn:aws:iam::909639744883:role/AmazonBedrockAgentCoreSDKRuntime-us-east-1-c980c3716d
      execution_role_auto_create: false
      account: '909639744883'
      region: us-east-1
      ecr_repository: 909639744883.dkr.ecr.us-east-1.amazonaws.com/bedrock-agentcore-agentcore_lang_runtime
      ecr_auto_create: false
      s3_path: null
      s3_auto_create: false
      network_configuration:
        network_mode: PUBLIC
        network_mode_config: null
      protocol_configuration:
        server_protocol: HTTP
      observability:
        enabled: true
      lifecycle_configuration:
        idle_runtime_session_timeout: null
        max_lifetime: null
    bedrock_agentcore:
      agent_id: agentcore_lang_runtime-5Nn6mH7wJR
      agent_arn: arn:aws:bedrock-agentcore:us-east-1:909639744883:runtime/agentcore_lang_runtime-5Nn6mH7wJR
      agent_session_id: 2287720c-f75b-4c6c-9909-6f9b9b9ac07f
    codebuild:
      project_name: bedrock-agentcore-agentcore_lang_runtime-builder
      execution_role: arn:aws:iam::909639744883:role/AmazonBedrockAgentCoreSDKCodeBuild-us-east-1-c980c3716d
      source_bucket: bedrock-agentcore-codebuild-sources-909639744883-us-east-1
    memory:
      mode: NO_MEMORY
      memory_id: null
      memory_arn: null
      memory_name: null
      event_expiry_days: 30
      first_invoke_memory_check_done: false
      was_created_by_toolkit: false
    identity:
      credential_providers: []
      workload: null
    aws_jwt:
      enabled: false
      audiences: []
      signing_algorithm: ES384
      issuer_url: null
      duration_seconds: 300
    authorizer_configuration: null
    request_header_configuration: null
    oauth_configuration: null
    api_key_env_var_name: null
    api_key_credential_provider_name: null
    is_generated_by_agentcore_create: false
  agentcore_memory:
    name: agentcore_memory
    entrypoint: /Users/sanjaydevarajan/Desktop/ML Projects/AgentCore/agentcore_memory.py
    deployment_type: container
    runtime_type: null
    platform: linux/arm64
    container_runtime: docker
    source_path: /Users/sanjaydevarajan/Desktop/ML Projects/AgentCore
    aws:
      execution_role: arn:aws:iam::909639744883:role/AmazonBedrockAgentCoreSDKRuntime-us-east-1-c5d93b0882
      execution_role_auto_create: false
      account: '909639744883'
      region: us-east-1
      ecr_repository: 909639744883.dkr.ecr.us-east-1.amazonaws.com/bedrock-agentcore-agentcore_memory
      ecr_auto_create: false
      s3_path: null
      s3_auto_create: false
      network_configuration:
        network_mode: PUBLIC
        network_mode_config: null
      protocol_configuration:
        server_protocol: HTTP
      observability:
        enabled: true
      lifecycle_configuration:
        idle_runtime_session_timeout: null
        max_lifetime: null
    bedrock_agentcore:
      agent_id: agentcore_memory-0w5gDqFoTJ
      agent_arn: arn:aws:bedrock-agentcore:us-east-1:909639744883:runtime/agentcore_memory-0w5gDqFoTJ
      agent_session_id: a7e3ff6c-1498-4d57-9dbc-76fb2fa8b1a0
    codebuild:
      project_name: bedrock-agentcore-agentcore_memory-builder
      execution_role: arn:aws:iam::909639744883:role/AmazonBedrockAgentCoreSDKCodeBuild-us-east-1-c5d93b0882
      source_bucket: bedrock-agentcore-codebuild-sources-909639744883-us-east-1
    memory:
      mode: STM_AND_LTM
      memory_id: customer_care_agent_memory-b0hSOA4DIl
      memory_arn: null
      memory_name: agentcore_memory_memory
      event_expiry_days: 30
      first_invoke_memory_check_done: false
      was_created_by_toolkit: false
    identity:
      credential_providers: []
      workload: null
    aws_jwt:
      enabled: false
      audiences: []
      signing_algorithm: ES384
      issuer_url: null
      duration_seconds: 300
    authorizer_configuration: null
    request_header_configuration: null
    oauth_configuration: null
    api_key_env_var_name: null
    api_key_credential_provider_name: null
    is_generated_by_agentcore_create: false
